# Generated by Django 3.1.1 on 2021-10-09 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_registration', '0016_auto_20211009_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='image_url',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
